### ISSUE TITLE
The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.

### ISSUE THREAD

**Issue by ghprod** [PonnamKarthik/FlutterToast#101]
Hi

I have an error when run debug

```
The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
See https://goo.gl/CP92wY for more information on the problem and how to fix it.
```
How to fix it?

Thanks

**Comment by jespitiaa** [comment]
I hope you had already solved this, but for future reference I will still comment.
Fortunately the package has been updated in order to support AndroidX since 2.2.0 or so. Make sure that you install the most recent version of the package in your pubspec.yaml (Or you can just leave the line without specifying a version, i.e: 
`fluttertoast:`
and the command pub packages get will just look for the latest version)

**Comment by PonnamKarthik** [comment]
@stiggy87 @jespitiaa @ghprod Check with `3.1.1`

**Comment by jespitiaa** [comment]
@stiggy87 I think that your project might have not fully migrated to AndroidX before using packages that are built on it, such as fluttertoast 3.1.0. If that is the case, I suggest following the steps on [this link](https://stackoverflow.com/questions/52409592/flutter-build-failed-with-an-exception/54394055#54394055) and checking every output of your console when you try to run your program

**Comment by jespitiaa** [comment]
> 
> 
> @PonnamKarthik Still failing. Looking at the analysis tab and seeing this: https://pub.dev/packages/fluttertoast#-analysis-tab-

I think that version 3.1.1 actually fails, considering the health of the package, but I have not upgraded yet and checked. My app works with 3.1.0 though

**Comment by PonnamKarthik** [comment]
@stiggy87 @jespitiaa I have fixed the issues please check and let me know

**Comment by stiggy87** [comment]
@PonnamKarthik Tested it with the 3.1.2 package and it builds locally on amd64.
