### ISSUE TITLE
[web] this plugin is not yet supporting flutter for web

### ISSUE THREAD

**Issue by jdeltoft** [PonnamKarthik/FlutterToast#128]
I tried this on my web app.  No dice.  no console errors either.  Just an FYI/request for this support if you have time.

**Comment by apgapg** [comment]
Yes please support for web and desktop

**Comment by enricobenedos** [comment]
I tried this package for flutter web because in the pub.dev it is loaded as compatible with web but in the supported platform paragraph it is specified that it works only with iOS and Android
![image](https://user-images.githubusercontent.com/12233746/72209509-5ba9d780-34af-11ea-9f86-81ef4bf0fe73.png)

**Comment by MoacirSchmidt** [comment]
Why is it listed as web compatible it it does not support web?

**Comment by PonnamKarthik** [comment]
Added Web Support check v4.0.0

**Comment by jdeltoft** [comment]
I noticed that timeInSecForIos is no longer there.
