### ISSUE TITLE
KotlinNullPointerException

### ISSUE THREAD

**Issue by GauthamAsir** [ponnamkarthik/FlutterToast#264]
E/flutter (25044): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: PlatformException(error, null, null, kotlin.KotlinNullPointerException
E/flutter (25044): 	at io.github.ponnamkarthik.toast.fluttertoast.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.kt:66)
E/flutter (25044): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/flutter (25044): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/flutter (25044): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
E/flutter (25044): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (25044): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/flutter (25044): 	at android.os.Looper.loop(Looper.java:183)
E/flutter (25044): 	at android.app.ActivityThread.main(ActivityThread.java:7661)
E/flutter (25044): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (25044): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:594)
E/flutter (25044): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/flutter (25044): )

Im getting this error recently.

**Comment by w568w** [comment]
Same with me. The KNP exception seems to be thrown at the line 68 :

https://github.com/ponnamkarthik/FlutterToast/blob/7e65255fcc5481a9842841647877fdd0a8401f21/android/src/main/kotlin/io/github/ponnamkarthik/toast/fluttertoast/MethodCallHandlerImpl.kt#L68

I suppose that `mToast.view` is null since [Android 11 behavior changes](https://stackoverflow.com/a/62885173). Custom toast views are deprecated.  
  
The easiest way is to replace `!!.` with `?.`, which is null safe. But custom text size will be unavailable.

**Comment by GauthamAsir** [comment]
> Same with me. The KNP exception seems to be thrown at the line 68 :
> 
> https://github.com/ponnamkarthik/FlutterToast/blob/7e65255fcc5481a9842841647877fdd0a8401f21/android/src/main/kotlin/io/github/ponnamkarthik/toast/fluttertoast/MethodCallHandlerImpl.kt#L68
> 
> I suppose that `mToast.view` is null since [Android 11 behavior changes](https://stackoverflow.com/a/62885173). Custom toast views are deprecated.
> 
> The easiest way is to replace `!!.` with `?.`, which is null safe. But custom text size will be unavailable.

Yes that's the reason, I too found out.
