### ISSUE TITLE
showing app icon in toast message

### ISSUE THREAD

**Issue by priyankassetcues** [ponnamkarthik/FlutterToast#379]
i dont want to show app icon in toast message. please help me how to avoid this problem.

**Comment by EinatK** [comment]
Same here, android 12, how do i remove it ?

**Comment by Ne0n11** [comment]
As i get the problem - its Android 12 new feature - to show the app icon from where toast message comes. As for now - they are fixing that feature, so that icon that loads is correct icon, and not generic icon as it is now. 
 And about your question - probably fluttertoast devs has not yet implemented a way to disable icon for Android 12 toasts.

Here is issue tracker that has some info on it:
https://issuetracker.google.com/issues/202863198?pli=1
