### ISSUE TITLE
web dependency is outdated now

### ISSUE THREAD

**Issue by MjnMixael** [ponnamkarthik/FlutterToast#524]
web is now 1.0.0 where this package depends on web 0.5.1

**Comment by zhao004** [comment]
**I also encountered this problem, how can I solve this?**
### ErrorMsg：
`Because cached_network_image >=3.4.1 depends on cached_network_image_web ^1.3.1 which depends on web ^1.0.0, cached_network_image >=3.4.1 requires web ^1.0.0.
And because fluttertoast 8.2.6 depends on web ^0.5.1 and no versions of fluttertoast match >8.2.6 <9.0.0, cached_network_image >=3.4.1 is incompatible with fluttertoast ^8.2.6.
So, because flutter_octopus_comics depends on both cached_network_image ^3.4.1 and fluttertoast ^8.2.6, version solving failed.
`

**Comment by ponnamkarthik** [comment]
Published new version thanks to @a-h-mzd  for the PR
